// src/components/push-setup-button.tsx
"use client";

import { useState, useEffect } from "react";
import { api } from "@/trpc/react";
import { toast } from "sonner";
import { env } from "@/env";

// Pulls directly from environment configuration
const VAPID_PUBLIC_KEY = env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; 

export function PushSetupButton() {
  const [isRegistering, setIsRegistering] = useState(false);
  const [permissionState, setPermissionState] = useState<NotificationPermission>("default");

  // Automatically check existing native permission status on mount
  useEffect(() => {
    if ("Notification" in window) {
      setPermissionState(Notification.permission);
    }
  }, []);

  // 1. Hook for saving the phone's subscription to PostgreSQL via Drizzle
  const mutation = api.notification.saveSubscription.useMutation({
    onSuccess: () => {
      toast.success("Phone registered for agenda push notifications!");
      setPermissionState("granted"); // Force local UI update immediately
    },
    onError: (err) => toast.error(`Failed saving to server: ${err.message}`),
  });

  // 2. Hook for broadcasting the secure test message payload from your backend
  const testMutation = api.notification.sendTestNotification.useMutation({
    onSuccess: () => toast.success("Notification payload dispatched from backend!"),
    onError: (err) => toast.error(`Error sending push: ${err.message}`),
  });

  const handleEnableNotifications = async () => {
    setIsRegistering(true);
    try {
      // 1. Check if browser supports system push
      if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
        throw new Error("Push notifications not supported on this mobile device.");
      }

      // 2. Request native OS permission
      const permission = await Notification.requestPermission();
      setPermissionState(permission);
      if (permission !== "granted") {
        throw new Error("Permission denied by user.");
      }

      // 3. Wait for our background public/sw.js registration to be fully ready
      const registration = await navigator.serviceWorker.ready;

      // 4. Generate/Fetch the browser token package from Apple or Google servers
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: VAPID_PUBLIC_KEY,
      });

      // 5. Format the cryptographic keys cleanly into string formats
      const rawSub = subscription.toJSON();
      if (!rawSub.endpoint || !rawSub.keys?.p256dh || !rawSub.keys?.auth) {
        throw new Error("Invalid token payload generated by device.");
      }

      // 6. Safely fire the payload straight to PostgreSQL via tRPC
      await mutation.mutateAsync({
        endpoint: rawSub.endpoint,
        keys: {
          p256dh: rawSub.keys.p256dh,
          auth: rawSub.keys.auth,
        },
      });

    } catch (error: any) {
      toast.error(error.message || "An unexpected error occurred.");
    } finally {
      setIsRegistering(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 p-4 border border-slate-800 rounded-2xl bg-slate-950/50 max-w-sm">
      <div className="text-xs font-semibold tracking-wide uppercase text-slate-500">
        Notification Testing Controls
      </div>
      
      {/* STEP 1: Enable Push/Sync Device */}
      {permissionState === "granted" ? (
        <div className="w-full px-4 py-2.5 bg-emerald-950/30 border border-emerald-500/20 text-emerald-400 rounded-xl text-center text-sm font-medium">
          ✅ Device Token Saved in Database
        </div>
      ) : permissionState === "denied" ? (
        <div className="w-full px-4 py-2.5 bg-red-950/40 border border-red-500/30 text-red-400 rounded-xl text-center text-sm font-medium">
          ❌ Notifications Blocked in Phone Settings
        </div>
      ) : (
        <button
          onClick={handleEnableNotifications}
          disabled={isRegistering}
          className="w-full px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-800 text-white rounded-xl font-medium shadow-md transition-all text-center text-sm"
        >
          {isRegistering ? "Syncing Device..." : "📱 Step 1: Enable Push Notifications"}
        </button>
      )}

      {/* STEP 2: Send Test Broadcast */}
      <button
        onClick={() => testMutation.mutate()}
        disabled={permissionState !== "granted" || testMutation.isPending}
        className="w-full px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-900 disabled:text-slate-600 border border-transparent disabled:border-slate-800 text-white rounded-xl font-medium shadow-md transition-all text-center text-sm"
      >
        {testMutation.isPending ? "Firing Payload..." : "🚀 Step 2: Send Test Push to Phone"}
      </button>
    </div>
  );
}
